### ISSUE TITLE
Convert local workarounds to PF overrides and file PF issues

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#686]
In https://github.com/cockpit-project/cockpit-files/pull/670, we added some local CSS that fixed the icon-only buttons and toggle sizing.

We need to promote these to PF5 overrides in Cockpit and re-import that back, to replace these snippets.

We also need to make sure PatternFly has issues opened for both.

```scss
// // FIXME: Promote the CSS below to overrides, open PF issues // //

// PatternFly always adds a margin after images inside of widgets with pf-m-end, which is incorrect when it's the last element
.pf-v5-c-button__icon.pf-m-start:last-child {
    margin-inline-end: 0;
}

// PF menu toggles are no longer spaced consistently
.pf-v5-c-menu-toggle {
    padding-inline: var(--pf-v5-global--spacer--md) calc(var(--pf-v5-global--spacer--md) * 0.75);
}
```
